package committee.nova.mods.avaritia_tweak.customization.render;

import committee.nova.mods.avaritia_tweak.customization.model.CustomizationEntry;
import committee.nova.mods.avaritia_tweak.customization.model.IngredientSpec;
import committee.nova.mods.avaritia_tweak.customization.model.ItemStackSpec;
import committee.nova.mods.avaritia_tweak.customization.model.OutputTarget;
import committee.nova.mods.avaritia_tweak.customization.model.WorkspaceSnapshot;

import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Set;

public final class CraftTweakerRenderer implements ArtifactRenderer {
    public static final ArtifactPath PATH = ArtifactPath.of("scripts/avaritia_tweak_generated.zs");

    @Override
    public Set<OutputTarget> supportedTargets() {
        return Set.of(OutputTarget.CRAFTTWEAKER);
    }

    @Override
    public List<RenderedArtifact> render(WorkspaceSnapshot snapshot) {
        StringBuilder script = new StringBuilder()
                .append("// Generated by Avaritia-Tweak visual editor. DO NOT EDIT.\n")
                .append("// Workspace schema: ").append(snapshot.schemaVersion()).append("\n");

        List<CustomizationEntry.SingularityOperation> operations = snapshot.entries().values().stream()
                .filter(entry -> entry.target() == OutputTarget.CRAFTTWEAKER)
                .filter(CustomizationEntry.SingularityOperation.class::isInstance)
                .map(CustomizationEntry.SingularityOperation.class::cast)
                .sorted(singularityOperationOrder())
                .toList();
        List<CustomizationEntry.SingularityDefinition> definitions = snapshot.entries().values().stream()
                .filter(entry -> entry.target() == OutputTarget.CRAFTTWEAKER)
                .filter(CustomizationEntry.SingularityDefinition.class::isInstance)
                .map(CustomizationEntry.SingularityDefinition.class::cast)
                .toList();
        List<CustomizationEntry> recipes = snapshot.entries().values().stream()
                .filter(entry -> entry.target() == OutputTarget.CRAFTTWEAKER && entry.kind().isRecipe())
                .toList();

        if (!operations.isEmpty() || !definitions.isEmpty() || !recipes.isEmpty()) {
            script.append('\n');
        }
        for (CustomizationEntry.SingularityOperation operation : operations) {
            String method = switch (operation.action()) {
                case REMOVE -> "remove";
                case REMOVE_ALL -> "removeAll";
                case REMOVE_RECIPE -> "removeRecipe";
                case REMOVE_ALL_RECIPES -> "removeAllRecipe";
            };
            script.append("mods.avaritia.Singularity.").append(method).append('(');
            operation.singularityId().ifPresent(id -> script.append(ScriptEscaper.quote(id.toString())));
            script.append(");\n");
        }
        if (!operations.isEmpty() && !definitions.isEmpty()) {
            script.append('\n');
        }
        for (CustomizationEntry.SingularityDefinition definition : definitions) {
            script.append("mods.avaritia.Singularity.register(")
                    .append(ScriptEscaper.quote(definition.id().toString())).append(", ")
                    .append(ScriptEscaper.quote(definition.displayName())).append(", ")
                    .append(rgb(definition.overlayColor())).append(", ")
                    .append(rgb(definition.underlayColor())).append(", ")
                    .append(definition.count()).append(", ")
                    .append(definition.timeCost()).append(", ")
                    .append(ingredient(definition.ingredient())).append(", ")
                    .append(definition.enabled()).append(", ")
                    .append(definition.recipeEnabled()).append(");\n");
        }
        if ((!operations.isEmpty() || !definitions.isEmpty()) && !recipes.isEmpty()) {
            script.append('\n');
        }
        for (int index = 0; index < recipes.size(); index++) {
            renderRecipe(script, recipes.get(index));
            if (index < recipes.size() - 1) {
                script.append('\n');
            }
        }
        return List.of(RenderedArtifact.text(PATH, script.toString()));
    }

    private static void renderRecipe(StringBuilder script, CustomizationEntry entry) {
        if (entry instanceof CustomizationEntry.ShapedTable shaped) {
            renderShaped(script, shaped);
        } else if (entry instanceof CustomizationEntry.ShapelessTable shapeless) {
            script.append("mods.avaritia.CraftingTable.addShapeless(\n")
                    .append("    ").append(ScriptEscaper.quote(shapeless.id().toString())).append(",\n")
                    .append("    ").append(shapeless.tier().value()).append(",\n")
                    .append("    ").append(itemStack(shapeless.result())).append(",\n");
            appendIngredientArray(script, shapeless.ingredients(), 4);
            script.append("\n);\n");
        } else if (entry instanceof CustomizationEntry.Compressor compressor) {
            script.append("mods.avaritia.Compressor.addRecipe(\n")
                    .append("    ").append(ScriptEscaper.quote(compressor.id().toString())).append(",\n")
                    .append("    ").append(ingredient(compressor.ingredient())).append(",\n")
                    .append("    ").append(itemStack(compressor.result())).append(",\n")
                    .append("    ").append(compressor.inputCount()).append(",\n")
                    .append("    ").append(compressor.timeCost()).append("\n")
                    .append(");\n");
        } else if (entry instanceof CustomizationEntry.ExtremeSmithing smithing) {
            script.append("mods.avaritia.ExtremeSmithing.addRecipe(\n")
                    .append("    ").append(ScriptEscaper.quote(smithing.id().toString())).append(",\n")
                    .append("    ").append(ingredient(smithing.template())).append(",\n")
                    .append("    ").append(ingredient(smithing.base())).append(",\n")
                    .append("    ").append(ingredient(smithing.addition())).append(",\n")
                    .append("    ").append(itemStack(smithing.result())).append("\n")
                    .append(");\n");
        } else if (entry instanceof CustomizationEntry.InfinityCatalyst catalyst) {
            script.append("mods.avaritia.CraftingTable.addCatalyst(\n")
                    .append("    ").append(ScriptEscaper.quote(catalyst.id().toString())).append(",\n")
                    .append("    ").append(ScriptEscaper.quote(catalyst.group())).append(",\n");
            appendIngredientArray(script, catalyst.ingredients(), 4);
            script.append(",\n    ").append(catalyst.count()).append("\n")
                    .append(");\n");
        } else if (entry instanceof CustomizationEntry.EternalSingularity eternal) {
            script.append("mods.avaritia.CraftingTable.addEnternal(\n")
                    .append("    ").append(ScriptEscaper.quote(eternal.id().toString())).append(",\n");
            appendIngredientArray(script, eternal.ingredients(), 4);
            script.append(",\n    ").append(eternal.count()).append("\n")
                    .append(");\n");
        } else {
            throw new IllegalArgumentException("Unsupported CraftTweaker recipe entry: " + entry.kind());
        }
    }

    private static void renderShaped(StringBuilder script, CustomizationEntry.ShapedTable shaped) {
        if (shaped.ingredients().isEmpty()) {
            throw new IllegalArgumentException("Cannot render an empty shaped recipe: " + shaped.id());
        }
        int size = shaped.tier().gridSize();
        int minRow = size;
        int maxRow = -1;
        int minColumn = size;
        int maxColumn = -1;
        for (int slot : shaped.ingredients().keySet()) {
            int row = slot / size;
            int column = slot % size;
            minRow = Math.min(minRow, row);
            maxRow = Math.max(maxRow, row);
            minColumn = Math.min(minColumn, column);
            maxColumn = Math.max(maxColumn, column);
        }

        script.append("mods.avaritia.CraftingTable.addShaped(\n")
                .append("    ").append(ScriptEscaper.quote(shaped.id().toString())).append(",\n")
                .append("    ").append(shaped.tier().value()).append(",\n")
                .append("    ").append(itemStack(shaped.result())).append(",\n")
                .append("    [\n");
        for (int row = minRow; row <= maxRow; row++) {
            script.append("        [");
            for (int column = minColumn; column <= maxColumn; column++) {
                if (column > minColumn) {
                    script.append(", ");
                }
                IngredientSpec ingredient = shaped.ingredients().get(row * size + column);
                script.append(ingredient == null ? "<item:minecraft:air>" : ingredient(ingredient));
            }
            script.append(row < maxRow ? "],\n" : "]\n");
        }
        script.append("    ]\n")
                .append(");\n");
    }

    private static void appendIngredientArray(StringBuilder script, List<IngredientSpec> ingredients,
                                              int indentation) {
        String outerIndent = " ".repeat(indentation);
        String itemIndent = " ".repeat(indentation + 4);
        script.append(outerIndent).append("[\n");
        for (int index = 0; index < ingredients.size(); index++) {
            script.append(itemIndent).append(ingredient(ingredients.get(index)));
            script.append(index < ingredients.size() - 1 ? ",\n" : "\n");
        }
        script.append(outerIndent).append(']');
    }

    static String ingredient(IngredientSpec ingredient) {
        if (ingredient instanceof IngredientSpec.Choice choice) {
            return choice.alternatives().stream()
                    .map(CraftTweakerRenderer::ingredient)
                    .collect(java.util.stream.Collectors.joining(" | ", "(", ")"));
        }
        if (ingredient instanceof IngredientSpec.Tag tag) {
            return "<tag:items:" + tag.tagId() + ">";
        }
        if (ingredient instanceof IngredientSpec.Components) {
            throw new IllegalArgumentException(
                    "NeoForge component predicates cannot be rendered losslessly for CraftTweaker");
        }
        IngredientSpec.Item item = (IngredientSpec.Item) ingredient;
        String base = "<item:" + item.itemId() + ">";
        return item.strictNbt()
                .map(nbt -> withCustomData(base, nbt))
                .orElse(base);
    }

    static String itemStack(ItemStackSpec stack) {
        String value = "<item:" + stack.itemId() + ">";
        if (stack.nbt().isPresent()) {
            value = withCustomData(value, stack.nbt().orElseThrow());
        }
        if (stack.count() != 1) {
            value += " * " + stack.count();
        }
        return value;
    }

    private static String withCustomData(String itemStack, net.minecraft.nbt.CompoundTag data) {
        return itemStack + ".withJsonComponent(<componenttype:minecraft:custom_data>, "
                + NbtText.canonical(data) + ")";
    }

    private static String rgb(int color) {
        return String.format(Locale.ROOT, "0x%06x", color);
    }

    private static Comparator<CustomizationEntry.SingularityOperation> singularityOperationOrder() {
        return Comparator.comparingInt((CustomizationEntry.SingularityOperation operation) -> switch (operation.action()) {
                    case REMOVE_ALL -> 0;
                    case REMOVE_ALL_RECIPES -> 1;
                    case REMOVE -> 2;
                    case REMOVE_RECIPE -> 3;
                })
                .thenComparing(operation -> operation.singularityId().map(Object::toString).orElse(""))
                .thenComparing(operation -> operation.id().toString());
    }
}
