package committee.nova.mods.avaritia_tweak.customization.render;

import committee.nova.mods.avaritia_tweak.customization.model.CustomizationEntry;
import committee.nova.mods.avaritia_tweak.customization.model.IngredientSpec;
import committee.nova.mods.avaritia_tweak.customization.model.ItemStackSpec;
import committee.nova.mods.avaritia_tweak.customization.model.OutputTarget;
import committee.nova.mods.avaritia_tweak.customization.model.SingularityAction;
import committee.nova.mods.avaritia_tweak.customization.model.WorkspaceSnapshot;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public final class KubeJsRenderer implements ArtifactRenderer {
    public static final ArtifactPath PATH = ArtifactPath.of(
            "kubejs/server_scripts/avaritia_tweak_generated.js");
    private static final List<Character> SHAPED_SYMBOLS = shapedSymbols();

    @Override
    public Set<OutputTarget> supportedTargets() {
        return Set.of(OutputTarget.KUBEJS);
    }

    @Override
    public List<RenderedArtifact> render(WorkspaceSnapshot snapshot) {
        StringBuilder script = new StringBuilder()
                .append("// Generated by Avaritia-Tweak visual editor. DO NOT EDIT.\n")
                .append("// Workspace schema: ").append(snapshot.schemaVersion()).append("\n\n");

        List<CustomizationEntry.SingularityOperation> operations = snapshot.entries().values().stream()
                .filter(entry -> entry.target() == OutputTarget.KUBEJS)
                .filter(CustomizationEntry.SingularityOperation.class::isInstance)
                .map(CustomizationEntry.SingularityOperation.class::cast)
                .sorted(singularityOperationOrder())
                .toList();
        List<CustomizationEntry.SingularityDefinition> definitions = snapshot.entries().values().stream()
                .filter(entry -> entry.target() == OutputTarget.KUBEJS)
                .filter(CustomizationEntry.SingularityDefinition.class::isInstance)
                .map(CustomizationEntry.SingularityDefinition.class::cast)
                .toList();
        if (!operations.isEmpty() || !definitions.isEmpty()) {
            renderSingularities(script, operations, definitions);
            script.append('\n');
        }

        script.append("ServerEvents.recipes(event => {\n")
                .append("    const { avaritia } = event.recipes;\n");
        List<CustomizationEntry> recipes = snapshot.entries().values().stream()
                .filter(entry -> entry.target() == OutputTarget.KUBEJS && entry.kind().isRecipe())
                .toList();
        if (!recipes.isEmpty()) {
            script.append('\n');
        }
        for (int index = 0; index < recipes.size(); index++) {
            renderRecipe(script, recipes.get(index));
            if (index < recipes.size() - 1) {
                script.append('\n');
            }
        }
        script.append("});\n");
        return List.of(RenderedArtifact.text(PATH, script.toString()));
    }

    private static void renderSingularities(StringBuilder script,
                                            List<CustomizationEntry.SingularityOperation> operations,
                                            List<CustomizationEntry.SingularityDefinition> definitions) {
        script.append("AvaritiaEvents.singularity(event => {\n");
        for (CustomizationEntry.SingularityOperation operation : operations) {
            String method = switch (operation.action()) {
                case REMOVE -> "remove";
                case REMOVE_ALL -> "removeAll";
                case REMOVE_RECIPE -> "removeRecipe";
                case REMOVE_ALL_RECIPES -> "removeAllRecipe";
            };
            script.append("    event.").append(method).append('(');
            operation.singularityId().ifPresent(id -> script.append(ScriptEscaper.quote(id.toString())));
            script.append(");\n");
        }
        if (!operations.isEmpty() && !definitions.isEmpty()) {
            script.append('\n');
        }
        for (int index = 0; index < definitions.size(); index++) {
            CustomizationEntry.SingularityDefinition definition = definitions.get(index);
            script.append("    event.register(")
                    .append(ScriptEscaper.quote(definition.id().toString()))
                    .append(", singularity => {\n")
                    .append("        singularity.setDisplayName(")
                    .append(ScriptEscaper.quote(definition.displayName())).append(")\n")
                    .append("            .setColors(")
                    .append(rgb(definition.overlayColor())).append(", ")
                    .append(rgb(definition.underlayColor())).append(")\n")
                    .append("            .setCount(").append(definition.count()).append(")\n")
                    .append("            .setTimeCost(").append(definition.timeCost()).append(")\n")
                    .append("            .setIngredient(Ingredient.of(")
                    .append(ingredient(definition.ingredient())).append("))\n")
                    .append("            .setEnabled(").append(definition.enabled()).append(")\n")
                    .append("            .setRecipeEnabled(").append(definition.recipeEnabled()).append(");\n")
                    .append("    });\n");
            if (index < definitions.size() - 1) {
                script.append('\n');
            }
        }
        script.append("});\n");
    }

    private static void renderRecipe(StringBuilder script, CustomizationEntry entry) {
        if (entry instanceof CustomizationEntry.ShapedTable shaped) {
            renderShaped(script, shaped);
        } else if (entry instanceof CustomizationEntry.ShapelessTable shapeless) {
            script.append("    avaritia.shapeless_table(\n")
                    .append("        ").append(shapeless.tier().value()).append(",\n")
                    .append("        ").append(itemStack(shapeless.result())).append(",\n");
            appendIngredientArray(script, shapeless.ingredients(), 8);
            script.append("\n    ).id(").append(ScriptEscaper.quote(shapeless.id().toString())).append(");\n");
        } else if (entry instanceof CustomizationEntry.Compressor compressor) {
            script.append("    avaritia.compressor(")
                    .append(ingredient(compressor.ingredient())).append(", ")
                    .append(itemStack(compressor.result())).append(")\n")
                    .append("        .inputCount(").append(compressor.inputCount()).append(")\n")
                    .append("        .timeCost(").append(compressor.timeCost()).append(")\n")
                    .append("        .id(").append(ScriptEscaper.quote(compressor.id().toString())).append(");\n");
        } else if (entry instanceof CustomizationEntry.ExtremeSmithing smithing) {
            script.append("    avaritia.extreme_smithing(\n")
                    .append("        ").append(itemStack(smithing.result())).append(",\n")
                    .append("        ").append(ingredient(smithing.template())).append(",\n")
                    .append("        ").append(ingredient(smithing.base())).append(",\n")
                    .append("        ").append(ingredient(smithing.addition())).append("\n")
                    .append("    ).id(").append(ScriptEscaper.quote(smithing.id().toString())).append(");\n");
        } else if (entry instanceof CustomizationEntry.InfinityCatalyst catalyst) {
            script.append("    avaritia.infinity_catalyst(\n")
                    .append("        ").append(ScriptEscaper.quote(catalyst.group())).append(",\n");
            appendIngredientArray(script, catalyst.ingredients(), 8);
            script.append(",\n        ").append(catalyst.count()).append("\n")
                    .append("    ).id(").append(ScriptEscaper.quote(catalyst.id().toString())).append(");\n");
        } else if (entry instanceof CustomizationEntry.EternalSingularity eternal) {
            script.append("    avaritia.eternal_singularity(\n");
            appendIngredientArray(script, eternal.ingredients(), 8);
            script.append(",\n        ").append(eternal.count()).append("\n")
                    .append("    ).id(").append(ScriptEscaper.quote(eternal.id().toString())).append(");\n");
        } else {
            throw new IllegalArgumentException("Unsupported KubeJS recipe entry: " + entry.kind());
        }
    }

    private static void renderShaped(StringBuilder script, CustomizationEntry.ShapedTable shaped) {
        if (shaped.ingredients().isEmpty()) {
            throw new IllegalArgumentException("Cannot render an empty shaped recipe: " + shaped.id());
        }
        int size = shaped.tier().gridSize();
        int minRow = size;
        int maxRow = -1;
        int minColumn = size;
        int maxColumn = -1;
        for (int slot : shaped.ingredients().keySet()) {
            int row = slot / size;
            int column = slot % size;
            minRow = Math.min(minRow, row);
            maxRow = Math.max(maxRow, row);
            minColumn = Math.min(minColumn, column);
            maxColumn = Math.max(maxColumn, column);
        }

        Map<IngredientSpec, Character> symbols = new LinkedHashMap<>();
        List<String> pattern = new ArrayList<>();
        for (int row = minRow; row <= maxRow; row++) {
            StringBuilder patternRow = new StringBuilder();
            for (int column = minColumn; column <= maxColumn; column++) {
                IngredientSpec ingredient = shaped.ingredients().get(row * size + column);
                if (ingredient == null) {
                    patternRow.append(' ');
                } else {
                    Character symbol = symbols.get(ingredient);
                    if (symbol == null) {
                        if (symbols.size() >= SHAPED_SYMBOLS.size()) {
                            throw new IllegalArgumentException("Too many unique shaped ingredients: " + shaped.id());
                        }
                        symbol = SHAPED_SYMBOLS.get(symbols.size());
                        symbols.put(ingredient, symbol);
                    }
                    patternRow.append(symbol);
                }
            }
            pattern.add(patternRow.toString());
        }

        script.append("    avaritia.shaped_table(\n")
                .append("        ").append(shaped.tier().value()).append(",\n")
                .append("        ").append(itemStack(shaped.result())).append(",\n")
                .append("        [\n");
        for (int index = 0; index < pattern.size(); index++) {
            script.append("            ").append(ScriptEscaper.quote(pattern.get(index)));
            script.append(index < pattern.size() - 1 ? ",\n" : "\n");
        }
        script.append("        ],\n")
                .append("        {\n");
        int index = 0;
        for (Map.Entry<IngredientSpec, Character> symbol : symbols.entrySet()) {
            script.append("            ").append(ScriptEscaper.quote(symbol.getValue().toString()))
                    .append(": ").append(ingredient(symbol.getKey()));
            script.append(index++ < symbols.size() - 1 ? ",\n" : "\n");
        }
        script.append("        }\n")
                .append("    ).id(").append(ScriptEscaper.quote(shaped.id().toString())).append(");\n");
    }

    private static void appendIngredientArray(StringBuilder script, List<IngredientSpec> ingredients,
                                              int indentation) {
        String outerIndent = " ".repeat(indentation);
        String itemIndent = " ".repeat(indentation + 4);
        script.append(outerIndent).append("[\n");
        for (int index = 0; index < ingredients.size(); index++) {
            script.append(itemIndent).append(ingredient(ingredients.get(index)));
            script.append(index < ingredients.size() - 1 ? ",\n" : "\n");
        }
        script.append(outerIndent).append(']');
    }

    static String ingredient(IngredientSpec ingredient) {
        if (ingredient instanceof IngredientSpec.Tag tag) {
            return ScriptEscaper.quote("#" + tag.tagId());
        }
        IngredientSpec.Item item = (IngredientSpec.Item) ingredient;
        return item.strictNbt()
                .map(nbt -> "Item.of(" + ScriptEscaper.quote(item.itemId().toString()) + ", "
                        + ScriptEscaper.quote(NbtText.canonical(nbt)) + ").strongNBT()")
                .orElseGet(() -> ScriptEscaper.quote(item.itemId().toString()));
    }

    static String itemStack(ItemStackSpec stack) {
        String itemId = ScriptEscaper.quote(stack.itemId().toString());
        if (stack.nbt().isPresent()) {
            String nbt = ScriptEscaper.quote(NbtText.canonical(stack.nbt().orElseThrow()));
            return stack.count() == 1
                    ? "Item.of(" + itemId + ", " + nbt + ")"
                    : "Item.of(" + itemId + ", " + stack.count() + ", " + nbt + ")";
        }
        return stack.count() == 1
                ? itemId
                : "Item.of(" + itemId + ", " + stack.count() + ")";
    }

    private static String rgb(int color) {
        return String.format(Locale.ROOT, "0x%06x", color);
    }

    private static Comparator<CustomizationEntry.SingularityOperation> singularityOperationOrder() {
        return Comparator.comparingInt((CustomizationEntry.SingularityOperation operation) -> switch (operation.action()) {
                    case REMOVE_ALL -> 0;
                    case REMOVE_ALL_RECIPES -> 1;
                    case REMOVE -> 2;
                    case REMOVE_RECIPE -> 3;
                })
                .thenComparing(operation -> operation.singularityId().map(Object::toString).orElse(""))
                .thenComparing(operation -> operation.id().toString());
    }

    private static List<Character> shapedSymbols() {
        List<Character> symbols = new ArrayList<>();
        for (char value = 33; value <= 126; value++) {
            if (value != '\'' && value != '"' && value != '\\') {
                symbols.add(value);
            }
        }
        return List.copyOf(symbols);
    }
}
